name: Mule Deploy
 
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
 
jobs:
  deploy:
    uses: Dbiz-MuleSoft/mulesoft-resuable-workflow/.github/workflows/mule-deploy.yml@main
    with:
         business_group: ${{ vars.BUSINESS_GROUP }}
    secrets: inherit
