name: Automated CloudHub Deployment

on:
  push:
    branches: [ main ] # Ensure this matches your branch name (main or master)
  workflow_call:
    inputs:
      anypoint_env:
        required: true
        type: string
      ch_target:
        required: true
        type: string
      business_group:
        required: true
        type: string
      app_runtime:
        required: false
        type: string
        default: '4.11.2:3e'
    secrets:
      ANYPOINT_CLIENT_ID:
        required: true
      ANYPOINT_CLIENT_SECRET:
        required: true  

jobs:
  deploy-mule-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          #cache: 'maven'

      - name: Create Maven settings for Exchange
        run: |
          - name: Create Maven settings for User Auth
       run: |
         mkdir -p "$HOME/.m2"
         #(cat > ~/.m2/settings.xml <<EOF)
         echo "<settings> 
                <servers>
                   <server>
                     <id>anypoint-exchange-v3</id>
                     <username>${{ secrets.ANYPOINT_USERNAME }}</username>
                     <password>${{ secrets.ANYPOINT_PASSWORD }}</password>
                   </server>
                </servers>
              </settings>" > "$HOME/.m2/settings.xml"

       shell: bash   

      # We skip creating the settings.xml for now to focus on a successful CloudHub deploy
      - name: Build, Install, and Deploy
        run: |
          # 1. 'install' forces the JAR into the local repository so plugins can "resolve" it.
          # 2. 'mule:deploy' handles the CloudHub 2.0 upload specifically.
          mvn clean install mule:deploy \
          -DmuleDeploy \
          -Dconnected.app.clientId="${{ secrets.ANYPOINT_CLIENT_ID }}" \
          -Dconnected.app.clientSecret="${{ secrets.ANYPOINT_CLIENT_SECRET }}" \
          -Danypoint.env="${{ secrets.ANYPOINT_ENV }}" \
          -Dch.target="${{ secrets.CH2_TARGET }}" \
          -Dapp.name="${{ github.event.repository.name }}-api" \
          -Dbusiness.group="${{ secrets.BUSINESS_GROUP }}" \
          -DgenerateDefaultPublicUrl=true \
          -DskipTests \
          -DskipPromotion=true \
          -DskipImageValidation=true
